In [1]:
import numpy as np

In [68]:
np.bincount(np.load('hist.npy'))

array([78, 19,  3])

In [49]:
176/10

17

In [55]:
np.abs(-5)

5

In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation

Using TensorFlow backend.


In [108]:
model = Sequential()
model.add(Dense(12, input_dim=6, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(2, activation='relu'))

In [109]:
model.compile(loss='mse',
              optimizer='sgd')

In [110]:
x = np.array([1, 2, 3, 4, 5, 7])
x = np.reshape(x, (1,6))

In [111]:
a = model.predict(x)

In [112]:
a

array([[ 0.22269867,  0.40227419]], dtype=float32)

In [113]:
target = 10 + 0.9 * a

In [114]:
target

array([[ 10.20042896,  10.3620472 ]], dtype=float32)

In [115]:
model.train_on_batch(x, target)

99.376099

In [116]:
b = model.predict(x)

In [117]:
b

array([[ 0.71092373,  9.85681915]], dtype=float32)

In [118]:
model.train_on_batch(x, target)

45.152981

In [78]:
model.predict(x)

array([[ 2.78326678]], dtype=float32)

In [81]:
np.array([[1, 2, 3]]).shape

(1, 3)

NameError: name 'shape' is not defined

In [83]:
np.array((1, 2, 3)).shape

(3,)

In [5]:
a = [1, 2, 3, 4, 5, 6]

In [54]:
b = np.random.choice(range(len(a)), 3, replace=False)

In [55]:
b

array([1, 2, 0])

In [51]:
a = [(25, 2),27, 21]

In [52]:
b = np.random.choice(a, 2, replace=False)

In [53]:
b

array([21, 27], dtype=object)